alias alacritty-conf="vim $HOME/.config/alacritty/alacritty.toml"
alias dot="EDITOR=nvim chezmoi"
alias fm="yazi"
alias hypr-conf="vim $HOME/.config/hypr/hyprland.conf"
alias hypr-restart="hyprctl dispatch exit"
alias nvim-conf="cd $HOME/.config/nvim && nvim ."
alias pn="pnpm"
alias vim="nvim"
alias vi="nvim"
alias waybar-refresh="pkill -SIGUSR2 waybar"
alias tmux-conf="vim $HOME/.tmux.conf"
alias zsh-alias="vim $ZSH/custom/aliases.zsh"
