[window]
padding = { x = 10, y = 10 }
opacity = 0.93

[font]
size = 12.0

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

[colors.primary]
background = "#0b1422"
